### ISSUE TITLE
Where to run idevice command?

### ISSUE THREAD

**Issue by Anon505950** [MiUnlockCode/MiUnlock#3]
I might just be stupid, but i don't know where to run the ideviceactivation activate -s http://example.com/activator.php command. I hosted my php site with apache2 and of course, ideviceactivation isn't a command. Please help my poor skid self! thanks

**Comment by cpablast** [comment]
Download libimobile open terminal or command and cd into libimobile folder, then run "ideviceactivation activate -s http://example.com/activator.php" without "" ... Also example.com to be replaced with your host ie yourhost.com.. This will not work on localhost
